[server]
headless = true
enableCORS = true
enableXsrfProtection = false
address = "0.0.0.0"
port = 5000
baseUrlPath = ""
maxUploadSize = 200
maxMessageSize = 200

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 5000

[logger]
level = "debug"
messageFormat = "%(asctime)s %(levelname)s %(message)s"