[server]
headless = true
enableCORS = true
enableXsrfProtection = false
address = "0.0.0.0"
port = 5000
baseUrlPath = ""
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 5000

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"